### ISSUE TITLE
Transition Axios readme to these docs

### ISSUE THREAD

**Issue by jasonsaayman** [axios/axios-docs#6]
We will need to find a way to transition the old Axios docs into these new docs & website. There are a number of links that will need to be updated throughout some files, we will also need to update canned prompts throughout the main repo.

**Comment by codemaster138** [comment]
@jasonsaayman Where do we stand on this? If you haven‘t done too much yet, I would be willing to set up a pull request where I distill only the most important information into the README and add a link to the documentation site.

I can‘t do this since I don‘t have maintainer status, but you should definitely add a link to the site up in the top right where the tags and description are

**Comment by jasonsaayman** [comment]
I have started by just adding a link to the new docs site. In a couple of weeks, I will add a warning about the depreciation of the current set of docs and the new doc's being kept here. Then we will need to cut down the docs in the readme to the most basic stuff, namely:

- New docs link
- How to install
- Simple example
